Vacation System/Models/DepartmentsViewModel.cs
using System.Collections.Generic;
using Vacation_System.ServiceReference;

namespace Vacation_System.Models
{
    public class DepartmentsViewModel
    {
       public List<DepartamentoMirror> Departamentos { get; set; }

       public string DisplayCreate { get; set; }

       public bool AllowDeactivate { get; set; }

        public DepartmentsViewModel()
        {
            Departamentos = new List<DepartamentoMirror>();
            DisplayCreate = "hidden";
            AllowDeactivate = false;
        }
    }
}

Vacation System/Models/EditUserViewModel.cs
namespace Vacation_System.Models
{
    public class EditUserViewModel : RegisterViewModel
    {
        public bool DisplayRolesAndDepartments { get; set; }
    }
}

Vacation System/Models/ProfileViewModel.cs
using Vacation_System.ServiceReference;

namespace Vacation_System.Models
{
    public class ProfileViewModel
    {
        public Empleado ProfileEmpleado { get; set; }

        public bool DisplayEditStatusBtn { get; set; }

        public bool DisplayEditBtn { get; set; }
    }
}

Vacation System/Models/RegisterViewModel.cs
using System.Collections.Generic;
using Vacation_System.ServiceReference;

namespace Vacation_System.Models
{
    public class RegisterViewModel
    {
        public Empleado Empleado { get; set; }

        public List<DepartamentoMirror> Departamentos { get; set; }

        public List<RolesMirror> Roles { get; set; } 
    }
}

Vacation System/Models/RequestViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Vacation_System.ServiceReference;

namespace Vacation_System.Models
{
    public class RequestViewModel
    {
        public List<Solicitud> Solicitudes { get; set; } 
    }
}

Vacation System/Models/UsersViewModel.cs
using System.Collections.Generic;
using Vacation_System.ServiceReference;

namespace Vacation_System.Models
{
    public class UsersViewModel
    {
        public List<UserMirror> Users { get; set; }

    }
}

Vacation System/Controllers/AccountPageController.cs
using System;
using System.Web.Mvc;
using Vacation_System.ServiceReference;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Vacation_System.Models;
using Web_Service;
using Vacation_System.Models;

namespace Vacation_System.Controllers
{
	public class AccountPageController : Controller
	{
		[HttpGet]
		public ActionResult Dashboard()
		{
			ServiceClient service = new ServiceClient();
			Empleado user = Session["User"] as Empleado;
			List<PendingVacations> pendientes = new List<PendingVacations>();

			if (user == null) return LogOut();

			Session["User"] = service.LoadVacaciones(Session["User"] as Empleado);
			user = Session["User"] as Empleado;
			user.YearC = (int)((DateTime.Now - user.User.FechaIngreso).TotalDays) / 365;
			user.DiasTomadosAnteriormente = user.Vacaciones.Where(vacacion => vacacion.Year == DateTime.Now.Year && vacacion.Estatus.Descripcion.Equals("Aprobado")).Sum(vacacion => vacacion.DiasSolicitados);

			user.DiasPendientesPorTomar = 23 - user.DiasTomadosAnteriormente;
			user.FechasNoDisponibles = user.Calendar.Select(x => x.fecha).ToArray();

			user.Vacaciones = user.Vacaciones.OrderBy(x => x.Year).ToArray();

			for (int i = 0; i < user.Vacaciones.Length; i++)
			{
				int available = 23;

				if (user.Vacaciones[i].DiasSolicitados < 23 && user.Vacaciones[i].Estatus.Descripcion.Equals("Aprobado"))
				{
					available -= user.Vacaciones[i].DiasSolicitados;
					while (i != (user.Vacaciones.Length - 1) && user.Vacaciones[i + 1].Year == user.Vacaciones[i].Year && user.Vacaciones[i+1].Estatus.Descripcion.Equals("Aprobado"))
					{
						available -= user.Vacaciones[i + 1].DiasSolicitados;
						i++;
					}

					pendientes.Add(new PendingVacations
					{
						PendingDays = available,
						PendingYear = user.Vacaciones[i].Year
					});
				}
			}

			ViewBag.VacacionesPendientes = pendientes;
			ViewBag.NotificationScript = "new PNotify({title: 'Enhorabuena', text: 'La solicitud ha sido enviada!', type: 'success'});";
			service.Close();

			return View(user);
		}

		[HttpPost]
		public RedirectToRouteResult Dashboard(VacacionesMirror vacaciones)
		{
			ServiceClient service = new ServiceClient();
			Empleado emp = (Session["User"] as Empleado);

			vacaciones.TalentoHumano = (Session["User"] as Empleado).User.TalentoHumano;
			vacaciones.FechaSolicitud = DateTime.Now;
			vacaciones.Year = DateTime.Today.Year;
			emp.Notification = true;

			service.AddVacation(vacaciones);
			service.Close();

			return RedirectToAction("Dashboard");
		}

		public ActionResult Profile()
		{
			if (Session["User"] == null) return LogOut();

			ProfileViewModel pvm = new ProfileViewModel
			{
				ProfileEmpleado = Session["User"] as Empleado,
				DisplayEditStatusBtn = false,
				DisplayEditBtn = true
			};

			return View(pvm);
		}

		public ActionResult Requests() {

			RequestViewModel rvm = new RequestViewModel();
			ServiceClient service = new ServiceClient();

			rvm.Solicitudes = service.LoadSolicitudes(((Empleado) Session["User"]).User.TalentoHumano).ToList();

			service.Close();

			return View(rvm);
		}

		[HttpPost]
		public RedirectToRouteResult Requests(string respuesta, int idSolicitud)
		{
			ServiceClient service = new ServiceClient();

			service.UpdateSolicitud(respuesta == "Aprobado", idSolicitud);

			service.Close();

		    return RedirectToAction("Dashboard");
		}

		[HttpGet]
		public ActionResult Departments()
		{
			if (Session["User"] == null) return LogOut();

			var emp = Session["User"] as Empleado;
			var dvm = new DepartmentsViewModel();

			var valido = false;

			foreach (var permiso in emp.Permisos)
			{
				switch (permiso.PermisosId)
				{
					case (int) PermisosEnum.EditarDepartamento:
						valido = true;
						break;
					case (int) PermisosEnum.CrearDepartamento:
						dvm.DisplayCreate = "button";
						break;
					case (int) PermisosEnum.DesactivarDepartamento:
						dvm.AllowDeactivate = true;
						break;
				}
			}

			if (!valido)
			{
				return RedirectToAction("error404", "Error");
			}

			ServiceClient service = new ServiceClient();

			dvm.Departamentos = service.LoadDepartments().ToList();

			service.Close();

			return View(dvm);
		}

		[HttpPost]
		public RedirectToRouteResult CreateDepartment(DepartamentoMirror departamentoMirror)
		{
			if(departamentoMirror.Descripcion == null)
				return RedirectToAction("Departments");

			ServiceClient service = new ServiceClient();

			service.CreateDepartment(departamentoMirror);

			service.Close();

			return RedirectToAction("Departments");
		}

		[HttpPost]
		public RedirectToRouteResult EditDepartment(DepartamentoMirror deptoEditado, string estatus)
		{
			if (deptoEditado == null) return RedirectToAction("Departments");

			ServiceClient service = new ServiceClient();

			if (estatus != null)
			{
				deptoEditado.Activo = !(estatus.Equals("True"));
			}

			service.EditDepartment(deptoEditado);

			service.Close();

			return RedirectToAction("Departments");
		}

		
		[HttpGet]
		public ActionResult Roles()
		{
			if (Session["User"] == null) return LogOut();

			Empleado emp = Session["User"] as Empleado;
			bool valido = false;

			foreach (var permiso in emp.Permisos)
			{
				if (permiso.PermisosId == (int)PermisosEnum.EditarRol ||
					permiso.PermisosId == (int)PermisosEnum.CrearRol)
				{
					valido = true;
				}
			}

			if (!valido)
			{
				return RedirectToAction("error404", "Error");
			}

			return View(new CreateRoleModel());
		}

		[HttpPost]
		public RedirectToRouteResult CreateRole(RolesMirror rolCreado)
		{
			if (rolCreado == null) return RedirectToAction("Error500", "Error");

			ServiceClient service = new ServiceClient();

			service.CreateRol(rolCreado);

			service.Close();

			return RedirectToAction("Roles");
		}

		[HttpPost]
		public RedirectToRouteResult EditRole(RolesMirror rolEditado)
		{
			if (rolEditado == null) return RedirectToAction("Error500", "Error");
			
			ServiceClient service = new ServiceClient();

			service.SaveRoleChanges(rolEditado);

			service.Close();

			return RedirectToAction("Roles");
		}
		
		
		public RedirectToRouteResult LogOut()
		{
			Session["User"] = null;

			return RedirectToAction("Index", "LogIn");
		}

		public ActionResult Register()
		{
			Empleado emp = Session["User"] as Empleado;
			bool valido = false;

			foreach (var permiso in emp.Permisos)
			{
				if (permiso.PermisosId == (int)PermisosEnum.CrearUsuario)
				{
					valido = true;
				}
			}

			if (!valido)
			{
				return RedirectToAction("error404", "Error");
			}

			ServiceClient service = new ServiceClient();

			RegisterViewModel rvm = new RegisterViewModel
			{
				Empleado = emp,
				Departamentos = service.LoadDepartments().ToList(),
				Roles = service.LoadRoles().ToList()
			};

			service.Close();

			return View(rvm);
		}

		[HttpPost]
		public RedirectToRouteResult Register(Empleado emp)
		{
			ServiceClient service = new ServiceClient();
			
			service.CreateUser(emp);

			service.Close();

			return RedirectToAction("Dashboard");
		}

		[HttpGet]
		public ActionResult Users()
		{
			ServiceClient client = new ServiceClient();

			UsersViewModel uvm = new UsersViewModel();

			uvm.Users = client.LoadUsers((Session["User"] as Empleado).User.Email).ToList();

			client.Close();

			return View(uvm);
		}

		public ActionResult UserProfile(int talentoHumano)
		{
			if (Session["User"] == null) return LogOut();

			ServiceClient service = new ServiceClient();

			ProfileViewModel pvm = new ProfileViewModel
			{
				ProfileEmpleado = service.LoadEmpleado(talentoHumano),
			};

			pvm.DisplayEditStatusBtn = (from p in (Session["User"] as Empleado).Permisos
								  where p.PermisosId == (int)PermisosEnum.DesactivarUsuario
								  select p).FirstOrDefault() != null;

			pvm.DisplayEditBtn = (from p in (Session["User"] as Empleado).Permisos
				where p.PermisosId == (int) PermisosEnum.EditarUsuario
				select p).FirstOrDefault() != null;
			
			service.Close();

			return View("Profile", pvm);
		}

		[HttpPost]
		public RedirectToRouteResult DesactivarUsuario(int talentoHumano, string edit)
		{
			ServiceClient service = new ServiceClient();

			service.EditUserStatus(talentoHumano, edit == "Activar");

			service.Close();

			return RedirectToAction("UserProfile", new { talentoHumano });
		}

		public ActionResult EditUser(int talentoHumano)
		{
			ServiceClient service = new ServiceClient();

			EditUserViewModel euvm = new EditUserViewModel
			{
				Empleado = service.LoadEmpleado(talentoHumano),
				Departamentos = service.LoadDepartments().ToList(),
				Roles = service.LoadRoles().ToList()
			};

			euvm.DisplayRolesAndDepartments = (Session["User"] as Empleado).User.TalentoHumano != 
				euvm.Empleado.User.TalentoHumano && 
				(from p in (Session["User"] as Empleado).Permisos
								  where p.PermisosId == (int)PermisosEnum.EditarUsuario
								  select p).FirstOrDefault() != null;

			service.Close();

			return View(euvm);
		}

		public RedirectToRouteResult EditarUser(Empleado empleado, string status)
		{
			ServiceClient service = new ServiceClient();

			empleado.User.Activo = status == "Activo";

			service.EditUser(empleado);

			service.Close();

			return RedirectToAction("Dashboard");
		}
	}
}

Vacation System/Views/AccountPage/Departments.cshtml
@model Vacation_System.Models.DepartmentsViewModel

@{
    Layout = "~/Views/AccountPage/Layout.cshtml";
    ViewBag.Title = "Departamentos";
}

<script>
    
    function closeModals(source) {
        var val = source.id;
        var text = "";
        var res = text.concat(val.toString());
        $(res).modal('hide');
    }

</script>

<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3> Editar Departamentos </h3>
        </div>

        <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Buscar...">
                    <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Go!</button>
                        </span>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Departamentos</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" 
                               aria-expanded="false">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu" role="menu"></ul>
                        </li>
                        <li>
                            <a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">

                    <div id="imgdepto" class="row">

                        @foreach (var departamento in Model.Departamentos)
                        {

                            <div class="col-md-55">
                                <div class="thumbnail">

                                    <div class="image view view-first">
                                        <img style="width: 130%;" src="~/Content/imgs/iconakatsuki.png" alt="image"/>

                                        <div class="mask" style="height: 100%">

                                            <p>
                                                <strong>
                                                    @departamento.Descripcion
                                                </strong>
                                            </p>

                                            <a href="#" data-target="#@departamento.Descripcion" data-toggle="modal">
                                                <i class="fa fa-pencil" style="color: #fff"></i>
                                            </a>

                                            @if (Model.AllowDeactivate)
                                            {
                                                if (departamento.Activo)
                                                {
                                                    <a href="#" data-target="#deac-@departamento.DepartamentoId" 
                                                       data-toggle="modal">
                                                        <i class="fa fa-times" style="color: #fff"></i>
                                                    </a>
                                                }
                                                else
                                                {
                                                    <a href="#" data-target="#deac-@departamento.DepartamentoId" 
                                                       data-toggle="modal">
                                                        <i class="fa fa-check" style="color: #fff"></i>
                                                    </a>
                                                }
                                            }

                                        </div>

                                    </div>

                                </div>
                            </div>


    <div id="@departamento.Descripcion" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">X</button>
                    <h3>Editar Departamento</h3>
                </div>

                @using (Html.BeginForm("EditDepartment", "AccountPage"))
                {

                    <div class="modal-body">

                        <input type="hidden" name="DepartamentoId" value="@departamento.DepartamentoId"/>
                        <input type="hidden" name="Activo" value="@departamento.Activo.ToString()"/>
                        
                        <h4>@departamento.Descripcion</h4>

                        <input type="text" name="Descripcion" class="form-control pull-right"
                               placeholder="Nuevo Nombre">


                    </div>
                    <div class="modal-footer">
                        <a href="#" class="btn" data-dismiss="modal">Close</a>
                        <input type="submit" id="@departamento.Descripcion" onclick="closeModals(this)" 
                               name="submit" value="Guardar Cambios"
                               class="btn btn-primary" />

                    </div>

                }



            </div>

        </div>

    </div>


    <div id="deac-@departamento.DepartamentoId" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">X</button>

                    @if (departamento.Activo)
                    {
                        <h3>Estas seguro de desactivar este departamento?</h3>
                    }
                    else
                    {
                        <h3>Estas seguro de re-activar este departamento?</h3>
                    }

                </div>

                @using (Html.BeginForm("EditDepartment", "AccountPage"))
                {
                    <div class="modal-footer">
                        
                        <input type="hidden" name="DepartamentoId" value="@departamento.DepartamentoId"/>
                        <input type="hidden" name="Descripcion" value="@departamento.Descripcion"/>
                        <input type="hidden" name="estatus" value="@departamento.Activo.ToString()" />

                        <button class="btn btn-primary" data-dismiss="modal">No</button>
                        <input type="submit" name="DesactivarDepto" value="Si"
                               class="btn btn-primary" />


                    </div>
                }

            </div>

        </div>

    </div>


                        }

                    </div>

                    <script>
                        
                        function addImg() {
                            $("#deptomodal").modal('hide');
                            var deptoname = document.getElementById("Descripcion").value;
                            if (deptoname !== "") {
                                $("#imgdepto").append("<div class='col-md-55'> <div class='thumbnail'>" +
                                    "<div class='image view view-first'><img style='width: 100%; display: " +
                                    "block;' src='../Content/imgs/iconakatsuki.png' alt='image' />" +
                                    "<div class='mask'><p>" + deptoname + "</p></div></div></div></div>");
                            }
                        }

                    </script>

                    <div class="col-md-offset-10">
                        <input type="@Model.DisplayCreate" class="btn btn-primary" id="Des" data-toggle="modal" 
                               data-target="#deptomodal" value="Agregar Nuevo"/>
                    </div>

                        <div id="deptomodal" class="modal fade" tabindex="-1" role="dialog">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">X</button>
                                        <h3>Agregar Departamento</h3>
                                    </div>

                                     @using (Html.BeginForm("CreateDepartment", "AccountPage"))
                                     {

                                    <div class="modal-body">

                                        <input type="text" name="Descripcion" class="form-control pull-right" 
                                               placeholder="Nombre">


                                    </div>
                                         <div class="modal-footer">
                                             <a href="#" class="btn" data-dismiss="modal">Close</a>
                                             <input type="submit" onclick="addImg();" name="submit" value="Guardar" 
                                                    class="btn btn-primary"/>

                                         </div>
                                         
                                     }

                                </div>

                            </div>

                        </div>

                </div>

            </div>
        </div>
    </div>
</div>

Vacation System/Views/AccountPage/Profile.cshtml
@model Vacation_System.Models.ProfileViewModel

@{
    Layout = "~/Views/AccountPage/Layout.cshtml";
    ViewBag.Title = "Perfil de "+@Model.ProfileEmpleado.User.PrimerNombre;
}

<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3>Perfil</h3>
        </div>
        <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Buscar...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">Ir</button>
                    </span>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">

                <div class="x_content">
                    <div class="col-md-3 col-sm-3 col-xs-12 profile_left">
                        <div class="profile_img">
                            <!-- end of image cropping -->
                            <div id="crop-avatar">
                                <!-- Current avatar -->
                                <div class="avatar-view" title="Cambiar foto de perfil">
                                    <img src="~/Content/imgs/img.png" alt="Avatar">
                                </div>
                                <!-- Cropping modal -->
                                <div class="modal fade" id="avatar-modal" aria-hidden="true" 
                                     aria-labelledby="avatar-modal-label" role="dialog" tabindex="-1">
                                    <div class="modal-dialog modal-lg">
                                        <div class="modal-content">
                                            <form class="avatar-form" action="crop.php" 
                                                  enctype="multipart/form-data" method="post">
                                                <div class="modal-header">
                                                    <button class="close" data-dismiss="modal" type="button">&times;</button>
                                                    <h4 class="modal-title" 
                                                        id="avatar-modal-label">Cambiar foto de perfil</h4>
                                                </div>
                                                <div class="modal-body">
                                                    <div class="avatar-body">
                                                        <!-- Upload image and data -->
                                                        <div class="avatar-upload">
                                                            <input class="avatar-src" name="avatar_src" type="hidden">
                                                            <input class="avatar-data" name="avatar_data" type="hidden">
                                                            <label for="avatarInput">Imagen local</label>
                                                            <input class="avatar-input" id="avatarInput" 
                                                                   name="avatar_file" type="file">
                                                        </div>
                                                        <!-- Crop and preview -->
                                                        <div class="row">
                                                            <div class="col-md-9">
                                                                <div class="avatar-wrapper"></div>
                                                            </div>
                                                            <div class="col-md-3">
                                                                <div class="avatar-preview preview-lg"></div>
                                                                <div class="avatar-preview preview-md"></div>
                                                                <div class="avatar-preview preview-sm"></div>
                                                            </div>
                                                        </div>
                                                        <div class="row avatar-btns">
                                                            <div class="col-md-3 pull-right">
                                                                <button class="btn btn-primary btn-block avatar-save" 
                                                                        type="submit">Guardar</button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <!-- <div class="modal-footer">
                                                  <button class="btn btn-default" data-dismiss="modal" type="button">Close</button>
                                                </div> -->
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <!-- /.modal -->
                                <!-- Loading state -->
                                <div class="loading" aria-label="Loading" role="img" tabindex="-1"></div>
                            </div>
                            <!-- end of image cropping -->
                        </div>
                        <h3>@Model.ProfileEmpleado.User.PrimerNombre @Model.ProfileEmpleado.User.SegundoNombre</h3>
                        <ul class="list-unstyled user_data">
                            <li>
                                <div class="fa fa-calendar user-profile-icon">
                                     @Model.ProfileEmpleado.User.FechaIngreso.ToString("dd/MM/yyyy")
                                </div>
                            </li>
                            <li>
                                <i class="fa fa-envelope user-profile-icon"> @Model.ProfileEmpleado.User.Email</i>
                            </li>
                            <li class="m-top-xs">
                                @{
                                    if (Model.ProfileEmpleado.User.Activo) 
                                    { 
                                        <i class="fa fa-check user-profile-icon">Activo</i>
                                        
                                    }
                                    else
                                    {
                                        <i class="fa fa-close user-profile-icon">Inactivo</i>
                                        
                                    }
                                }
                            </li>
                        </ul>

                        @if (Model.DisplayEditBtn)
                        {
                            <a class="btn btn-success" href="@Url.Action("EditUser",
                                                                 new { talentoHumano = Model.ProfileEmpleado.User.TalentoHumano })">

                                <i class="fa fa-edit m-right-xs"></i>Editar Perfil

                            </a>
                        }


                        @if (Model.DisplayEditStatusBtn)
                        {
                            using (Html.BeginForm("DesactivarUsuario", "AccountPage"))
                            {
                                <input type="hidden" name="talentoHumano" value="@Model.ProfileEmpleado.User.TalentoHumano" />

                                if (Model.ProfileEmpleado.User.Activo)
                                {
                                    <input class="btn btn-danger" type="submit" name="edit" value="Desactivar" />
                                }
                                else
                                {
                                    <input class="btn btn-primary" type="submit" name="edit" value="Activar" />
                                }
                            }
                        }

                        <br />

                    </div>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        <!--Insert intelligent user info-->
                        <h2 class="center-block"></h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Vacation System/Views/AccountPage/Users.cshtml
@model Vacation_System.Models.UsersViewModel

@{
    ViewBag.Title = "Users";
    Layout = "~/Views/AccountPage/Layout.cshtml";
}
<div class="clearfix"></div>

<script>
    var row;
    $(document).ready(function () {
        row = $('#example').dataTable({
            columnDefs: [{
                targets: [0],
                orderData: [0, 0]
            }, ]
        });
    });
</script>
<table id="example" class="display" cellspacing="0" width="100%">

    <thead>
        <tr>
            <th>Nombre</th>
        </tr>
    </thead>

    <tbody>



        @foreach (var user in Model.Users)
        {
            <tr>
                <td>
                    <a href="@Url.Action("UserProfile", new {talentoHumano = user.TalentoHumano})">
                        @user.PrimerNombre @user.PrimerApellido
                    </a>
                </td>
            </tr>
        }

    </tbody>

</table>
@*@foreach (var user in Model.Users)
    {
        <li>
            <a href="@Url.Action("UserProfile", new {talentoHumano = user.TalentoHumano})">
                @user.PrimerNombre @user.PrimerApellido
            </a>
        </li>
        <br/>
        <br/>
    }*@